project_id = "hroghyzosrcjueqjftex"

[functions.generate-prompts]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.generate-image-seedream]
verify_jwt = false

[functions.generate-descriptions]
verify_jwt = false

